name: Build Geode Mod (Docker)

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

env:
  MOD_ID: alk.allium

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          target: windows
          artifact-name: geode-build-win

        - name: macOS
          target: macos
          artifact-name: geode-build-mac

        - name: iOS
          target: ios
          artifact-name: geode-build-ios

        - name: Android32
          target: android32
          artifact-name: geode-build-android32

        - name: Android64
          target: android64
          artifact-name: geode-build-android64

    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build ${{ matrix.config.name }}
      uses: docker/build-push-action@v6
      with:
        context: .
        target: export-${{ matrix.config.target }}
        build-args: |
          MOD_ID=${{ env.MOD_ID }}
        outputs: type=local,dest=./out
        cache-from: type=gha,scope=geode-mod-${{ matrix.config.target }}
        cache-to: type=gha,mode=max,compression=zstd,compression-level=8,scope=geode-mod-${{ matrix.config.target }}
      env:
        DOCKER_BUILD_SUMMARY: false

    - name: Upload ${{ matrix.config.name }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config.artifact-name }}
        path: ./out

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
    - uses: geode-sdk/build-geode-mod/combine@main
      id: build

    - uses: actions/upload-artifact@v4
      with:
        name: Build Output
        path: ${{ steps.build.outputs.build-output }}